# Generated by Django 5.1.1 on 2025-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')], max_length=10),
        ),
    ]
